"""CfD scheme module — ARCHITECTURE §6.1 contract.

Five module-level callables satisfying the `SchemeModule` Protocol (declared
in `uk_subsidy_tracker.schemes.__init__`). This is the template Phase 5
(Renewables Obligation) and every subsequent scheme module copies.

Public surface:
- `DERIVED_DIR`: where this scheme's Parquet lives (`data/derived/cfd/`).
- `upstream_changed()`: sha-compare against sidecars (Plan 04-02 substrate).
- `refresh()`: re-fetch raw sources (thin wrapper here; Plan 04-05 orchestrates).
- `rebuild_derived(output_dir)`: full raw → Parquet derivation.
- `regenerate_charts()`: delegate to `uk_subsidy_tracker.plotting.__main__`.
- `validate()`: sanity checks; returns human-readable warning strings.

Protocol conformance is validated at runtime:
    >>> from uk_subsidy_tracker.schemes import cfd, SchemeModule
    >>> isinstance(cfd, SchemeModule)
    True
"""
from __future__ import annotations

from pathlib import Path

from uk_subsidy_tracker import PROJECT_ROOT
from uk_subsidy_tracker.counterfactual import METHODOLOGY_VERSION
from uk_subsidy_tracker.schemes.cfd._refresh import (
    refresh as _refresh,
    upstream_changed as _upstream_changed,
)
from uk_subsidy_tracker.schemes.cfd.aggregation import (
    build_annual_summary,
    build_by_allocation_round,
    build_by_technology,
)
from uk_subsidy_tracker.schemes.cfd.cost_model import build_station_month
from uk_subsidy_tracker.schemes.cfd.forward_projection import build_forward_projection

DERIVED_DIR: Path = PROJECT_ROOT / "data" / "derived" / "cfd"


def upstream_changed() -> bool:
    """Return True iff any raw file's sha256 differs from its sidecar."""
    return _upstream_changed()


def refresh() -> None:
    """Re-fetch LCCC/Elexon/ONS raw files (delegates to _refresh.refresh)."""
    _refresh()


def rebuild_derived(output_dir: Path | None = None) -> None:
    """Emit the five CfD derived Parquet grains under the target directory.

    Pure function of `data/raw/` content (D-21). If `output_dir` is None,
    writes to `DERIVED_DIR = data/derived/cfd/`. Otherwise writes to the
    caller-supplied path (test fixtures depend on this).

    Order matters: build_station_month first (canonical upstream grain);
    the three rollups read `station_month.parquet` back to exercise the
    round-trip path and guarantee rollup consistency (D-03).
    """
    target = output_dir if output_dir is not None else DERIVED_DIR
    target.mkdir(parents=True, exist_ok=True)
    build_station_month(target)
    build_annual_summary(target)
    build_by_technology(target)
    build_by_allocation_round(target)
    build_forward_projection(target)


def regenerate_charts() -> None:
    """Delegate to the existing plotting entry point (D-02 — charts untouched).

    Charts are regenerated by the chart-orchestration module, which is a
    Phase 0-1 concern orthogonal to the derived-layer build. This function
    exists to satisfy the SchemeModule contract; Plan 04-05's refresh
    workflow calls it after `rebuild_derived()`.
    """
    import runpy

    runpy.run_module("uk_subsidy_tracker.plotting", run_name="__main__")


def validate() -> list[str]:
    """Return a list of human-readable warnings (empty list = all clean).

    Three checks (D-discretion default set):
    1. Latest-year row count within ±10% of previous year (partial-year
       detection; refresh clobbered late data, etc).
    2. No null `technology` in station_month (portfolio join completeness).
    3. `methodology_version` column agrees with live constant (no staleness).
    """
    import pyarrow.parquet as pq

    warnings: list[str] = []
    station_month = DERIVED_DIR / "station_month.parquet"
    if not station_month.exists():
        return [f"validate: {station_month} missing — run rebuild_derived()"]
    df = pq.read_table(station_month).to_pandas()

    # Check 1: latest-year row count within ±10% of previous year.
    df["year"] = df["month_end"].dt.year
    yearly = df.groupby("year").size().sort_index()
    if len(yearly) >= 2:
        latest, previous = int(yearly.iloc[-1]), int(yearly.iloc[-2])
        if previous > 0 and abs(latest - previous) / previous > 0.10:
            warnings.append(
                f"validate: latest-year row count drift > 10% "
                f"({previous} -> {latest})"
            )

    # Check 2: no null technology.
    if df["technology"].isna().any():
        warnings.append("validate: null technology in station_month")

    # Check 3: methodology_version matches constant.
    unique_versions = df["methodology_version"].unique().tolist()
    if len(unique_versions) != 1 or unique_versions[0] != METHODOLOGY_VERSION:
        warnings.append(
            f"validate: methodology_version drift — column has {unique_versions!r}, "
            f"constant is {METHODOLOGY_VERSION!r}"
        )

    return warnings


__all__ = [
    "DERIVED_DIR",
    "upstream_changed",
    "refresh",
    "rebuild_derived",
    "regenerate_charts",
    "validate",
]
