"""CfD total cost vs gas counterfactual — monthly and cumulative.

Two-panel chart with shared x-axis:
- Top: monthly bars decomposing CfD cost into gas counterfactual + premium.
- Bottom: cumulative stacked area — orange = gas counterfactual, blue =
  CfD premium. Total height = total CfD cost to consumers.

The 2022 gas spike shows as a brief dip in the monthly premium (green bars)
but barely registers in the cumulative view — the "CfDs saved money" narrative
is a tiny notch in a rising curve.

Sources:
- LCCC "Actual CfD Generation and avoided GHG emissions" — provides daily
  generation (MWh) and strike price (£/MWh) per CfD unit.
- ONS System Average Price of gas — daily wholesale gas price in p/kWh
  (thermal), as paid by gas suppliers.

CfD cost (the blue + orange total):
- CfD cost = sum(strike_price × generation_MWh) across all units per month.
- The strike price is the all-in guaranteed price per MWh. Consumers pay it
  via two channels: the wholesale market price (on their electricity bill)
  plus the CfD levy top-up. The sum always equals the strike price.
- This includes the generator's capital cost recovery — the strike price
  was set at auction to cover building and operating the wind/solar farm.

Gas counterfactual (the orange area — "what gas would have cost"):
- Answers: "if we'd built gas CCGT plants instead, what would the fuel
  cost have been to generate the same MWh?"
- Computed daily: gas_price_p_per_kWh × 10 / 0.55 = £/MWh electricity.
  The ×10 converts p/kWh to £/MWh. Dividing by 0.55 (CCGT thermal
  efficiency) accounts for fuel wasted as heat — 1.82 kWh of gas is
  burned per 1 kWh of electricity produced.
- Daily gas electricity cost (£/MWh) is multiplied by the actual daily
  CfD generation (MWh), then summed to monthly totals. Using daily
  granularity captures intra-month gas price spikes (e.g. Beast from
  the East, 2022 crisis) rather than smoothing them with a monthly average.

Premium (the blue area — "extra cost of CfD policy"):
- Premium = CfD cost − gas counterfactual.
- This is the net cost of choosing CfDs over gas for that electricity.

What's excluded (and why it matters):
- Carbon tax (UK ETS ~£36-53/tCO2): excluded from the gas side to show
  the pure fuel comparison. Including it would reduce the premium.
- Gas plant capital costs: excluded. The CfD strike price includes capital
  recovery but the gas counterfactual is fuel-only, so the comparison
  slightly overstates the CfD premium.
- 55% CCGT efficiency is representative of modern plants. Using a lower
  efficiency (e.g. 50%) would make gas look more expensive and shrink
  the apparent premium.
"""

import plotly.graph_objects as go

from cfd_payment.counterfactual import compute_counterfactual
from cfd_payment.data import load_lccc_dataset
from cfd_payment.plotting import ChartBuilder


def _prepare_monthly():
    df = load_lccc_dataset("Actual CfD Generation and avoided GHG emissions")
    cf_daily = compute_counterfactual(carbon_prices={})
    gas_price = cf_daily.set_index("date")["gas_fuel_cost"]

    df["month"] = df["Settlement_Date"].dt.to_period("M").dt.to_timestamp()
    df["strike_times_gen"] = df["Strike_Price_GBP_Per_MWh"] * df["CFD_Generation_MWh"]

    daily_gen = df.groupby("Settlement_Date")["CFD_Generation_MWh"].sum()
    daily_gas_cost = daily_gen * gas_price.reindex(daily_gen.index)

    monthly_cfd = df.groupby("month")["strike_times_gen"].sum()
    monthly_gas = daily_gas_cost.resample("ME").sum()
    monthly_gas.index = monthly_gas.index.to_period("M").to_timestamp()

    monthly = monthly_cfd.to_frame("cfd_cost").join(
        monthly_gas.rename("gas_cost"), how="inner"
    )
    monthly["premium"] = monthly["cfd_cost"] - monthly["gas_cost"]
    return monthly


def main() -> None:
    monthly = _prepare_monthly()

    monthly_m = monthly / 1e6
    cum_bn = monthly.cumsum() / 1e9

    builder = ChartBuilder(
        title="What CfD electricity cost vs what the same electricity would cost from gas (no carbon tax)",
        height=900,
    )
    fig = builder.create_subplots(
        rows=2,
        cols=1,
        shared_xaxes=True,
        subplot_titles=[
            "Monthly — CfD cost decomposed",
            f"Cumulative — £{cum_bn['cfd_cost'].iloc[-1]:.0f}bn total spent on CfD electricity",
        ],
        vertical_spacing=0.08,
    )

    # --- Top panel: monthly bars ---
    fig.add_trace(
        go.Bar(
            x=monthly_m.index,
            y=monthly_m["gas_cost"],
            name="Cost if generated by gas",
            marker_color="#ff7f0e",
            hovertemplate="%{x|%b %Y}<br>Gas: £%{y:.0f}m<extra></extra>",
        ),
        row=1,
        col=1,
    )

    positive = monthly_m["premium"].clip(lower=0)
    negative = monthly_m["premium"].clip(upper=0)

    fig.add_trace(
        go.Bar(
            x=monthly_m.index,
            y=positive,
            name="Extra cost of CfD policy",
            marker_color="#1f77b4",
            hovertemplate="%{x|%b %Y}<br>Premium: £%{y:.0f}m<extra></extra>",
        ),
        row=1,
        col=1,
    )

    fig.add_trace(
        go.Bar(
            x=monthly_m.index,
            y=negative,
            name="CfD saving vs gas",
            marker_color="#2ca02c",
            hovertemplate="%{x|%b %Y}<br>Saving: £%{y:.0f}m<extra></extra>",
        ),
        row=1,
        col=1,
    )

    # --- Bottom panel: cumulative stacked area ---
    fig.add_trace(
        go.Scatter(
            x=cum_bn.index,
            y=cum_bn["gas_cost"],
            name=f"What gas would have cost (£{cum_bn['gas_cost'].iloc[-1]:.0f}bn)",
            mode="lines",
            line={"color": "#ff7f0e", "width": 2},
            fill="tozeroy",
            fillcolor="rgba(255,127,14,0.4)",
            stackgroup="cumulative",
            hovertemplate="%{x|%b %Y}<br>Gas: £%{y:.1f}bn<extra></extra>",
        ),
        row=2,
        col=1,
    )

    fig.add_trace(
        go.Scatter(
            x=cum_bn.index,
            y=cum_bn["premium"],
            name=f"Extra cost of CfD policy (£{cum_bn['premium'].iloc[-1]:.0f}bn)",
            mode="lines",
            line={"color": "#1f77b4", "width": 2},
            fill="tonexty",
            fillcolor="rgba(31,119,180,0.4)",
            stackgroup="cumulative",
            hovertemplate="%{x|%b %Y}<br>Premium: £%{y:.1f}bn<extra></extra>",
        ),
        row=2,
        col=1,
    )

    fig.update_layout(
        barmode="relative",
        hovermode="x unified",
    )

    builder.format_currency_axis(
        fig,
        axis="y",
        suffix="m",
        title="£ millions",
        row=1,
        col=1,
    )
    builder.format_currency_axis(
        fig,
        axis="y",
        suffix="bn",
        title="£ billions",
        row=2,
        col=1,
    )

    builder.save(fig, "subsidy_cfd_vs_gas_total", export_twitter=True)


if __name__ == "__main__":
    main()
